<template><div><h1 id="getting-started" tabindex="-1"><a class="header-anchor" href="#getting-started" aria-hidden="true">#</a> Getting Started</h1>
<p>Kotlin is an object oriented langiage with functional features</p>
<h2 id="variables" tabindex="-1"><a class="header-anchor" href="#variables" aria-hidden="true">#</a> Variables</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">var</span> a<span class="token operator">:</span> Int <span class="token operator">=</span> <span class="token number">0</span> <span class="token comment">// variable</span>
a <span class="token operator">=</span> <span class="token number">23</span>

<span class="token keyword">val</span> b<span class="token operator">:</span> String <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"Hello"</span></span> <span class="token comment">// immutable variable</span>
b <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"World"</span></span> <span class="token comment">//error</span>

<span class="token keyword">var</span> b <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"Hello"</span></span> <span class="token comment">// Type is inferred</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Use val as much as possible</li>
<li><em>In kotlin, semi-colons are optionnal</em></li>
</ul>
<!---
Author: Yassine BENABBAS
--->
<hr>
<h2 id="functions" tabindex="-1"><a class="header-anchor" href="#functions" aria-hidden="true">#</a> Functions</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token comment">// Functions can be declared outside of classes</span>
<span class="token keyword">fun</span> <span class="token function">sum</span><span class="token punctuation">(</span>x<span class="token operator">:</span>Int<span class="token punctuation">,</span> y<span class="token operator">:</span>Int<span class="token punctuation">)</span> <span class="token operator">:</span> Int <span class="token punctuation">{</span>
    <span class="token keyword">return</span> x <span class="token operator">+</span> y
<span class="token punctuation">}</span> <span class="token comment">// function definition</span>

<span class="token comment">//One line function</span>
<span class="token keyword">fun</span> <span class="token function">mult</span><span class="token punctuation">(</span>x<span class="token operator">:</span>Int<span class="token punctuation">,</span> y<span class="token operator">:</span> Int<span class="token punctuation">)</span> <span class="token operator">=</span> x <span class="token operator">*</span> y

<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span>argv<span class="token operator">:</span>Array<span class="token operator">&lt;</span>String<span class="token operator">></span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">val</span> a <span class="token operator">=</span> <span class="token function">sum</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token comment">// call sum function</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token function">mult</span><span class="token punctuation">(</span>a<span class="token punctuation">,</span> y <span class="token operator">=</span> <span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// we can name parameters</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="functions-arguments" tabindex="-1"><a class="header-anchor" href="#functions-arguments" aria-hidden="true">#</a> Functions arguments</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">greet</span><span class="token punctuation">(</span>year<span class="token operator">:</span> Int <span class="token operator">=</span> <span class="token number">2018</span><span class="token punctuation">,</span> month<span class="token operator">:</span> Int <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">,</span>
          message<span class="token operator">:</span> String <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"Hello"</span></span><span class="token punctuation">)</span> <span class="token operator">:</span> String <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token string-literal singleline"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">message</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">. We are in </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">month</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">year</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span>
<span class="token punctuation">}</span>

<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span>argv<span class="token operator">:</span>Array<span class="token operator">&lt;</span>String<span class="token operator">></span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token function">greet</span><span class="token punctuation">(</span><span class="token number">2017</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token string-literal singleline"><span class="token string">"Bonjour"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">//Bonjour. We are in 10/2017</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token function">greet</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">//Hello. We are in 1/2018</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token function">greet</span><span class="token punctuation">(</span><span class="token number">2018</span><span class="token punctuation">,</span> message <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"Konnichiwa"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token comment">//Konnichiwa. We are in 1/2018</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="classes" tabindex="-1"><a class="header-anchor" href="#classes" aria-hidden="true">#</a> Classes</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">open</span> <span class="token keyword">class</span> Pokemon <span class="token comment">// class with default constructor</span>
<span class="token keyword">class</span> <span class="token function">PokemonTrainer</span><span class="token punctuation">(</span><span class="token keyword">val</span> name<span class="token operator">:</span> String<span class="token punctuation">,</span> <span class="token keyword">val</span> pokemon<span class="token operator">:</span> Pokemon<span class="token punctuation">)</span>

<span class="token comment">// classes are final by default. Open allows to inherit</span>
<span class="token keyword">class</span> <span class="token function">Pikachu</span><span class="token punctuation">(</span><span class="token keyword">val</span> Watts<span class="token operator">:</span> Int<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token function">Pokemon</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">val</span> pika <span class="token operator">=</span> <span class="token function">Pikachu</span><span class="token punctuation">(</span><span class="token number">2000</span><span class="token punctuation">)</span> <span class="token comment">// type inferred</span>
    <span class="token keyword">val</span> ash <span class="token operator">=</span> <span class="token function">PokemonTrainer</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"ash"</span></span><span class="token punctuation">,</span> pika<span class="token punctuation">)</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">ash<span class="token punctuation">.</span>name</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">, your pokemon object is </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">pika</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
    <span class="token comment">// ash, your pokemon object is Pikachu@2ff4acd0</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="classes-2" tabindex="-1"><a class="header-anchor" href="#classes-2" aria-hidden="true">#</a> Classes 2</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">data</span> <span class="token keyword">class</span> <span class="token function">Potion</span><span class="token punctuation">(</span><span class="token keyword">var</span> hp<span class="token operator">:</span> Int<span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">var</span> timesConsumed <span class="token operator">=</span> <span class="token number">0</span> <span class="token comment">// define member variable</span>
    <span class="token keyword">fun</span> <span class="token function">consume</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        hp <span class="token operator">-=</span> <span class="token number">20</span> <span class="token punctuation">;</span>  timesConsumed <span class="token operator">+=</span> <span class="token number">1</span> <span class="token comment">// avoid multi. statements on same line</span>
    <span class="token punctuation">}</span> <span class="token comment">// member function</span>
<span class="token punctuation">}</span> <span class="token comment">//data generates hashCode, equals, copy and toString</span>
<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">val</span> p1 <span class="token operator">=</span> <span class="token function">Potion</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">)</span>
    <span class="token keyword">val</span> p2 <span class="token operator">=</span> <span class="token function">Potion</span><span class="token punctuation">(</span><span class="token number">80</span><span class="token punctuation">)</span>
    <span class="token function">println</span><span class="token punctuation">(</span>p1 <span class="token operator">==</span> p2<span class="token punctuation">)</span> <span class="token comment">// false</span>
    p1<span class="token punctuation">.</span><span class="token function">consume</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// call member function</span>
    <span class="token function">println</span><span class="token punctuation">(</span>p1 <span class="token operator">==</span> p2<span class="token punctuation">)</span> <span class="token comment">// true even if timesConsumed !=</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="control-flow" tabindex="-1"><a class="header-anchor" href="#control-flow" aria-hidden="true">#</a> Control flow</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">var</span> n <span class="token operator">=</span> <span class="token number">2</span>
    <span class="token keyword">var</span> isPair <span class="token operator">=</span> <span class="token keyword">if</span> <span class="token punctuation">(</span> n <span class="token operator">%</span> <span class="token number">2</span> <span class="token operator">==</span> <span class="token number">0</span> <span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token boolean">true</span>
    <span class="token punctuation">}</span><span class="token keyword">else</span><span class="token punctuation">{</span>
        <span class="token boolean">false</span>
    <span class="token punctuation">}</span> <span class="token comment">// If statements can return a value</span>
    <span class="token function">println</span><span class="token punctuation">(</span>isPair<span class="token punctuation">)</span>
    n <span class="token operator">=</span> <span class="token number">11</span>
    isPair <span class="token operator">=</span> <span class="token keyword">if</span><span class="token punctuation">(</span> n <span class="token operator">%</span> <span class="token number">2</span> <span class="token operator">==</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token boolean">true</span> <span class="token keyword">else</span> <span class="token boolean">false</span>
    <span class="token function">println</span><span class="token punctuation">(</span>isPair<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="control-flow-when" tabindex="-1"><a class="header-anchor" href="#control-flow-when" aria-hidden="true">#</a> Control flow : when</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">val</span> greeting <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"Bonjour"</span></span>
    <span class="token comment">// when is a more powerful switch</span>
    <span class="token comment">// It works also on strings</span>
    <span class="token keyword">val</span> language <span class="token operator">=</span> <span class="token keyword">when</span><span class="token punctuation">(</span>greeting<span class="token punctuation">)</span><span class="token punctuation">{</span>
       <span class="token string-literal singleline"><span class="token string">"Bonjour"</span></span><span class="token punctuation">,</span><span class="token string-literal singleline"><span class="token string">"salut"</span></span> <span class="token operator">-></span> <span class="token string-literal singleline"><span class="token string">"Français"</span></span>
        <span class="token string-literal singleline"><span class="token string">"Good morning"</span></span> <span class="token operator">-></span> <span class="token string-literal singleline"><span class="token string">"English"</span></span>
        <span class="token keyword">else</span> <span class="token operator">-></span> <span class="token string-literal singleline"><span class="token string">"Unknown"</span></span>
    <span class="token punctuation">}</span>
    <span class="token function">println</span><span class="token punctuation">(</span>language<span class="token punctuation">)</span> <span class="token comment">// Français</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="control-flow-loops" tabindex="-1"><a class="header-anchor" href="#control-flow-loops" aria-hidden="true">#</a> Control flow: loops</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span>i <span class="token keyword">in</span> <span class="token number">1</span><span class="token operator">..</span><span class="token number">3</span><span class="token punctuation">)</span> <span class="token function">println</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span> <span class="token comment">// single line</span>
	<span class="token keyword">for</span> <span class="token punctuation">(</span>i <span class="token keyword">in</span> <span class="token number">6</span> downTo <span class="token number">0</span> step <span class="token number">2</span><span class="token punctuation">)</span> <span class="token function">println</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span>msg <span class="token keyword">in</span> <span class="token function">arrayOf</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"Hello"</span></span><span class="token punctuation">,</span> <span class="token string-literal singleline"><span class="token string">"world"</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    	<span class="token function">println</span><span class="token punctuation">(</span>msg<span class="token punctuation">)</span>
	<span class="token punctuation">}</span>
    <span class="token keyword">var</span> x <span class="token operator">=</span> <span class="token number">2</span>
    <span class="token keyword">while</span> <span class="token punctuation">(</span>x <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    	x<span class="token operator">--</span>
	<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="higher-order-functions" tabindex="-1"><a class="header-anchor" href="#higher-order-functions" aria-hidden="true">#</a> Higher order functions</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">calculate</span><span class="token punctuation">(</span>x<span class="token operator">:</span> Int<span class="token punctuation">,</span> y<span class="token operator">:</span> Int<span class="token punctuation">,</span> f<span class="token operator">:</span> <span class="token punctuation">(</span>Int<span class="token punctuation">,</span> Int<span class="token punctuation">)</span> <span class="token operator">-></span> Int<span class="token punctuation">)</span> <span class="token operator">:</span> Int<span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token function">f</span><span class="token punctuation">(</span>x<span class="token punctuation">,</span> y<span class="token punctuation">)</span>
<span class="token punctuation">}</span> <span class="token comment">// calculate takes a function as a paramter</span>
<span class="token keyword">fun</span> <span class="token function">sum</span><span class="token punctuation">(</span>x<span class="token operator">:</span> Int<span class="token punctuation">,</span> y<span class="token operator">:</span> Int<span class="token punctuation">)</span> <span class="token operator">=</span> x <span class="token operator">+</span> y
<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token function">calculate</span><span class="token punctuation">(</span><span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token operator">::</span>sum<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 14</span>
    <span class="token keyword">val</span> f <span class="token operator">=</span> <span class="token punctuation">{</span>x<span class="token operator">:</span> Int<span class="token punctuation">,</span> y<span class="token operator">:</span> Int <span class="token operator">-></span> x <span class="token operator">-</span> y<span class="token punctuation">}</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token function">calculate</span><span class="token punctuation">(</span><span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> f<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 4</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token function">calculate</span><span class="token punctuation">(</span><span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> x<span class="token punctuation">,</span> y <span class="token operator">-></span> x <span class="token operator">*</span> y <span class="token punctuation">}</span> <span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 45</span>
    <span class="token comment">// If the last parameter is function, we can close () erlier</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token function">calculate</span><span class="token punctuation">(</span><span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> x<span class="token punctuation">,</span> y <span class="token operator">-></span> x <span class="token operator">*</span> y <span class="token punctuation">}</span> <span class="token punctuation">)</span> <span class="token comment">// 45</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="naive-foreach-implementation" tabindex="-1"><a class="header-anchor" href="#naive-foreach-implementation" aria-hidden="true">#</a> Naive forEach implementation</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token comment">// Unit means no return value (it is optionnal)</span>
<span class="token keyword">fun</span> <span class="token function">naiveForEach</span><span class="token punctuation">(</span>items<span class="token operator">:</span> List<span class="token operator">&lt;</span>Int<span class="token operator">></span><span class="token punctuation">,</span> f<span class="token operator">:</span> <span class="token punctuation">(</span>Int<span class="token punctuation">)</span> <span class="token operator">-></span> Unit<span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">for</span><span class="token punctuation">(</span>item <span class="token keyword">in</span> items<span class="token punctuation">)</span> <span class="token function">f</span><span class="token punctuation">(</span>item<span class="token punctuation">)</span>
<span class="token punctuation">}</span> <span class="token comment">// Naive implementation of forEeach</span>
<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">val</span> numbers <span class="token operator">=</span> <span class="token function">listOf</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span>
    <span class="token function">naiveForEach</span><span class="token punctuation">(</span>numbers<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token function">println</span><span class="token punctuation">(</span>it <span class="token operator">*</span> <span class="token number">10</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span> <span class="token comment">// The it parameter is implcit for signle arg fun</span>

    <span class="token comment">// Kotlin defines a forEach method for collections</span>
    numbers<span class="token punctuation">.</span><span class="token function">forEach</span> <span class="token punctuation">{</span> <span class="token function">println</span><span class="token punctuation">(</span>it <span class="token operator">*</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="extensions" tabindex="-1"><a class="header-anchor" href="#extensions" aria-hidden="true">#</a> Extensions</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token comment">// we can extend existing classes with functions</span>
<span class="token keyword">fun</span> String<span class="token punctuation">.</span><span class="token function">makeQuestion</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token keyword">this</span> <span class="token operator">+</span> <span class="token string-literal singleline"><span class="token string">" ?"</span></span>
<span class="token comment">// And getters / setters</span>
<span class="token keyword">val</span> Int<span class="token punctuation">.</span>isPair <span class="token keyword">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token keyword">this</span> <span class="token operator">%</span> <span class="token number">2</span> <span class="token operator">==</span> <span class="token number">0</span>
<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">val</span> s <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"Are you OK"</span></span>
    <span class="token keyword">val</span> q <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">makeQuestion</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"s: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">s</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">, q: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">q</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
    <span class="token comment">// s: Are you OK, q: Are you OK ?</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">.</span>isPair<span class="token punctuation">)</span> <span class="token comment">// true</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="null-safety" tabindex="-1"><a class="header-anchor" href="#null-safety" aria-hidden="true">#</a> <a href="https://kotlinlang.org/docs/reference/null-safety.html" target="_blank" rel="noopener noreferrer">Null safety<ExternalLinkIcon/></a></h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">var</span> s<span class="token operator">:</span> String <span class="token comment">// vars must be initialized before using</span>
    <span class="token comment">// println(s) -> compile fails</span>
    s <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"hello"</span></span>
    <span class="token function">println</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token comment">// ok</span>
    <span class="token comment">// s = null -> compile fails. Types are not nullable</span>
    <span class="token keyword">val</span> msg <span class="token operator">:</span> String<span class="token operator">?</span> <span class="token operator">=</span> <span class="token keyword">null</span> <span class="token comment">// nullable types</span>
    <span class="token function">println</span><span class="token punctuation">(</span>msg<span class="token punctuation">)</span>
    <span class="token comment">// msg.reversed() // msg may be null -> compile ko</span>
    <span class="token function">println</span><span class="token punctuation">(</span>msg<span class="token operator">?</span><span class="token punctuation">.</span><span class="token function">reversed</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">?</span><span class="token punctuation">.</span><span class="token function">capitalize</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// return null if any part is null</span>
    <span class="token function">println</span><span class="token punctuation">(</span>msg<span class="token operator">!!</span><span class="token punctuation">.</span><span class="token function">reversed</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// tell compiler to ignore null checks -> NPE</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="null-safety-part-2" tabindex="-1"><a class="header-anchor" href="#null-safety-part-2" aria-hidden="true">#</a> <a href="https://kotlinlang.org/docs/reference/null-safety.html" target="_blank" rel="noopener noreferrer">Null safety - part 2<ExternalLinkIcon/></a></h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">var</span> nb<span class="token operator">:</span> Int<span class="token operator">?</span> <span class="token operator">=</span> <span class="token number">2</span>
    <span class="token comment">// kotlin compiler known that nb is never null in else</span>
    <span class="token keyword">val</span> double <span class="token operator">=</span> <span class="token keyword">if</span><span class="token punctuation">(</span> nb <span class="token operator">==</span> <span class="token keyword">null</span> <span class="token punctuation">)</span> <span class="token number">0</span> <span class="token keyword">else</span> nb <span class="token operator">*</span> <span class="token number">2</span>
    <span class="token function">println</span><span class="token punctuation">(</span>double<span class="token punctuation">)</span>
    <span class="token comment">// shortcut of prev if using ?: elvis operator</span>
    <span class="token keyword">val</span> triple <span class="token operator">=</span> nb<span class="token operator">?</span><span class="token punctuation">.</span><span class="token function">times</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span> <span class="token operator">?:</span> <span class="token number">0</span> <span class="token punctuation">;</span> <span class="token function">println</span><span class="token punctuation">(</span>triple<span class="token punctuation">)</span>
    <span class="token comment">//safe cast return nullable and does not throw exception</span>
    <span class="token keyword">val</span> newNb <span class="token operator">=</span> nb <span class="token keyword">as</span><span class="token operator">?</span> Long <span class="token punctuation">;</span>  <span class="token function">println</span><span class="token punctuation">(</span>newNb<span class="token punctuation">)</span>
    <span class="token comment">// Convert nullable list to non nullable one</span>
    <span class="token keyword">val</span> nullableList<span class="token operator">:</span> List<span class="token operator">&lt;</span>Int<span class="token operator">?</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token function">listOf</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">)</span>
	<span class="token keyword">val</span> intList<span class="token operator">:</span> List<span class="token operator">&lt;</span>Int<span class="token operator">></span> <span class="token operator">=</span> nullableList<span class="token punctuation">.</span><span class="token function">filterNotNull</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">println</span><span class="token punctuation">(</span>intList<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="java-kotlin-ineroperability" tabindex="-1"><a class="header-anchor" href="#java-kotlin-ineroperability" aria-hidden="true">#</a> Java &lt;-&gt; Kotlin ineroperability</h2>
<ul>
<li>Kotlin is designed with Java interoperability in mind</li>
<li>Kotlin code may require annotation to be called from Java</li>
<li>It is much more easier and natural to call Java from Kotli
<ul>
<li>For example: Java getter and Setter is converter to Kotlin propoerty</li>
</ul>
</li>
</ul>
<h2 id="java-from-kotlin-example" tabindex="-1"><a class="header-anchor" href="#java-from-kotlin-example" aria-hidden="true">#</a> Java from Kotlin example</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">import</span> java<span class="token punctuation">.</span>util<span class="token punctuation">.</span><span class="token operator">*</span>
<span class="token keyword">fun</span> <span class="token function">convertToArrayList</span><span class="token punctuation">(</span>source<span class="token operator">:</span> List<span class="token operator">&lt;</span>Int<span class="token operator">></span><span class="token punctuation">)</span><span class="token operator">:</span> ArrayList<span class="token operator">&lt;</span>Int<span class="token operator">></span> <span class="token punctuation">{</span>
    <span class="token comment">// instantiate as in Java without 'new'</span>
    <span class="token keyword">val</span> list <span class="token operator">=</span> ArrayList<span class="token operator">&lt;</span>Int<span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token comment">// 'for'-loops work for Java collections:</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span>item <span class="token keyword">in</span> source<span class="token punctuation">)</span> list<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>item<span class="token punctuation">)</span>
    <span class="token comment">// get and set are called</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span>i <span class="token keyword">in</span> <span class="token number">0</span><span class="token operator">..</span>source<span class="token punctuation">.</span>size <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">)</span> list<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> source<span class="token punctuation">[</span>i<span class="token punctuation">]</span>
    <span class="token keyword">return</span> list
<span class="token punctuation">}</span>
<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">val</span> list <span class="token operator">=</span> <span class="token function">convertToArrayList</span><span class="token punctuation">(</span><span class="token function">listOf</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"list: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">list</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">. type: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">list<span class="token operator">::</span><span class="token keyword">class</span><span class="token punctuation">.</span>qualifiedName</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
    <span class="token comment">//list: [0, 2, -1]. type: java.util.ArrayList</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="destructuring" tabindex="-1"><a class="header-anchor" href="#destructuring" aria-hidden="true">#</a> Destructuring</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token comment">// Destructuring allows to get different properties at once</span>
<span class="token keyword">data</span> <span class="token keyword">class</span> <span class="token function">Result</span><span class="token punctuation">(</span><span class="token keyword">val</span> code<span class="token operator">:</span>Int<span class="token punctuation">,</span> <span class="token keyword">val</span> message<span class="token operator">:</span>String<span class="token punctuation">)</span>
<span class="token keyword">fun</span> <span class="token function">makeComputation</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span>Result <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token function">Result</span><span class="token punctuation">(</span><span class="token number">200</span><span class="token punctuation">,</span> <span class="token string-literal singleline"><span class="token string">"Success"</span></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token comment">// data class and Pair allows the following</span>
    <span class="token keyword">val</span> <span class="token punctuation">(</span>code<span class="token punctuation">,</span> message<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token function">makeComputation</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"code: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">code</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">. Message: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">message</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
    <span class="token comment">// works also on maps</span>
    <span class="token keyword">val</span> map <span class="token operator">=</span> <span class="token function">mapOf</span><span class="token punctuation">(</span><span class="token number">1</span> <span class="token keyword">to</span> <span class="token string-literal singleline"><span class="token string">"am"</span></span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span> <span class="token keyword">to</span> <span class="token string-literal singleline"><span class="token string">"stram"</span></span><span class="token punctuation">,</span> <span class="token number">5</span> <span class="token keyword">to</span> <span class="token string-literal singleline"><span class="token string">"gram"</span></span><span class="token punctuation">)</span>
    <span class="token keyword">for</span><span class="token punctuation">(</span><span class="token punctuation">(</span>k<span class="token punctuation">,</span>v<span class="token punctuation">)</span> <span class="token keyword">in</span> map<span class="token punctuation">)</span> <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"key: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">k</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">, value: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">v</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="function-with-receiver" tabindex="-1"><a class="header-anchor" href="#function-with-receiver" aria-hidden="true">#</a> Function with receiver</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">produce</span><span class="token punctuation">(</span><span class="token keyword">init</span><span class="token operator">:</span> MilkProducer<span class="token punctuation">.</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-></span> Unit<span class="token punctuation">)</span><span class="token operator">:</span> MilkProducer <span class="token punctuation">{</span>
    <span class="token keyword">val</span> producer <span class="token operator">=</span> <span class="token function">MilkProducer</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    producer<span class="token punctuation">.</span><span class="token function">init</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">return</span> producer
<span class="token punctuation">}</span>
<span class="token keyword">class</span> MilkProducer<span class="token punctuation">{</span>
    <span class="token keyword">val</span> isSuccessful <span class="token operator">=</span> <span class="token boolean">false</span>
    <span class="token keyword">fun</span> <span class="token function">success</span><span class="token punctuation">(</span>handler<span class="token operator">:</span> MilkProducer<span class="token punctuation">.</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span> Unit<span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token keyword">if</span><span class="token punctuation">(</span>isSuccessful<span class="token punctuation">)</span> <span class="token function">handler</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">fun</span> <span class="token function">failure</span><span class="token punctuation">(</span>handler<span class="token operator">:</span> MilkProducer<span class="token punctuation">.</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span>Unit<span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span>isSuccessful<span class="token punctuation">)</span> <span class="token function">handler</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    produce <span class="token punctuation">{</span>
        success <span class="token punctuation">{</span> <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"Success !"</span></span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
        failure <span class="token punctuation">{</span> <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"Failure !"</span></span><span class="token punctuation">)</span> <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="kotlin-for-android" tabindex="-1"><a class="header-anchor" href="#kotlin-for-android" aria-hidden="true">#</a> Kotlin for Android</h2>
<ul>
<li>Kotlin simplifies Android development</li>
<li><a href="https://kotlinlang.org/docs/tutorials/android-plugin.html" target="_blank" rel="noopener noreferrer">Kotlin extensions<ExternalLinkIcon/></a> eliminate the need to use <code v-pre>findViewById</code></li>
<li><em>Note</em>: annotation dependencies are not the same than in Java</li>
<li>Links:
<ul>
<li><a href="https://kotlinlang.org/docs/tutorials/kotlin-android.html" target="_blank" rel="noopener noreferrer">Getting started with Android and Kotlin<ExternalLinkIcon/></a></li>
<li><a href="https://kotlinlang.org/docs/tutorials/android-plugin.html" target="_blank" rel="noopener noreferrer">Kotlin Android Extensions <ExternalLinkIcon/></a></li>
</ul>
</li>
</ul>
<h2 id="coroutines" tabindex="-1"><a class="header-anchor" href="#coroutines" aria-hidden="true">#</a> Coroutines</h2>
<p>Requires maven dependency: org.jetbrains.kotlinx:kotlinx-coroutines-core</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"Start"</span></span><span class="token punctuation">)</span>
<span class="token comment">// Start a coroutine</span>
GlobalScope<span class="token punctuation">.</span><span class="token function">launch</span> <span class="token punctuation">{</span>
    <span class="token function">delay</span><span class="token punctuation">(</span><span class="token number">1000</span><span class="token punctuation">)</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"Hello"</span></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"Stop"</span></span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>This will crash</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> c <span class="token operator">=</span> <span class="token function">AtomicLong</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

<span class="token keyword">for</span> <span class="token punctuation">(</span>i <span class="token keyword">in</span> <span class="token number">1</span><span class="token operator">..</span><span class="token number">1_000_000L</span><span class="token punctuation">)</span>
    <span class="token function">thread</span><span class="token punctuation">(</span>start <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        c<span class="token punctuation">.</span><span class="token function">addAndGet</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

<span class="token function">println</span><span class="token punctuation">(</span>c<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>With coroutines it does not crash</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> c <span class="token operator">=</span> <span class="token function">AtomicLong</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

<span class="token keyword">for</span> <span class="token punctuation">(</span>i <span class="token keyword">in</span> <span class="token number">1</span><span class="token operator">..</span><span class="token number">1_000_000L</span><span class="token punctuation">)</span>
    GlobalScope<span class="token punctuation">.</span><span class="token function">launch</span> <span class="token punctuation">{</span>
        c<span class="token punctuation">.</span><span class="token function">addAndGet</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

<span class="token function">println</span><span class="token punctuation">(</span>c<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
