# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "*" # Group all updates
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/docs/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "*" # Group all updates
  - package-ecosystem: "gradle"
    directories: 
      - "/material/*"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "*" # Group all updates
  - package-ecosystem: "pip"
    directory: "/material/rest-api-ui-ktor-quiz-collector/result-explorer/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "*" # Group all updates
