/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package null_safety_java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
