/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.worldline.learningkt.samples;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class NullSafetySample {

    public static void main(String[] args) {
        int length = getLength(null);
        @Nonnull String name;
        name = null; // warning
        
        // warning (there is no optional chaining operator ?.)
        @Nullable String name2;
        name2 = null;
        System.out.println(name2.length()); 
        System.out.println(name2 == null ? 0 : name2.length());
        getLength(null);
    }

//    public static int getLength(String name) {
//        return name.length();
//    }
    
    public static int getLength(String text) {
        return text == null ? 0 : text.length();
    }
    
    public static int getLength3(@Nullable String text) {
        return text.length();
    }
    

    public static int getLength4(@Nullable String text) {
        if (text == null){
            return 0;
        }
        return text.length();
    }

}
